// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`, `runtime`, `stream_url_for`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Engine`

/// Initialise the torrent engine. `download_dir` must be an app-writable
/// directory (e.g. from `path_provider`). Returns the local HTTP server port.
/// Idempotent: later calls just return the existing port.
Future<int> initTorrentEngine({required String downloadDir}) => RustLib
    .instance
    .api
    .crateApiTorrentInitTorrentEngine(downloadDir: downloadDir);

/// Add a torrent from a magnet link (or an http(s) `.torrent` URL). Resolves
/// metadata, then returns the file list plus a stream URL for the largest file.
Future<AddedTorrent> addTorrent({required String magnet}) =>
    RustLib.instance.api.crateApiTorrentAddTorrent(magnet: magnet);

/// Build the stream URL for a specific file in a torrent.
String getStreamUrl({required int torrentId, required int fileIndex}) => RustLib
    .instance
    .api
    .crateApiTorrentGetStreamUrl(torrentId: torrentId, fileIndex: fileIndex);

/// Result of adding a torrent: everything the UI needs to start streaming.
class AddedTorrent {
  final int id;
  final String name;
  final List<TorrentFile> files;

  /// Index of the largest file — the one to stream by default (the video).
  final int primaryFileIndex;

  /// Ready-to-play URL for the primary file.
  final String streamUrl;

  const AddedTorrent({
    required this.id,
    required this.name,
    required this.files,
    required this.primaryFileIndex,
    required this.streamUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      files.hashCode ^
      primaryFileIndex.hashCode ^
      streamUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddedTorrent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          files == other.files &&
          primaryFileIndex == other.primaryFileIndex &&
          streamUrl == other.streamUrl;
}

/// A single file inside a torrent.
class TorrentFile {
  final int index;
  final String name;
  final BigInt length;

  const TorrentFile({
    required this.index,
    required this.name,
    required this.length,
  });

  @override
  int get hashCode => index.hashCode ^ name.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentFile &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          length == other.length;
}
